name: Deno Deploy

on:
  push:
    paths:
      - "code/**"
      - "main.ts"
      - "deno.json"
      - ".github/workflows/deploy.yml"

jobs:
  deploy-pbl-work:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install deployctl
        run: deno install -gArf jsr:@deno/deployctl

      - name: Deploy PBL
        run: |
          echo "Deploying..."
          echo "Deno Deploy Token: ${{ secrets.PBL }}"
          deployctl deploy --org=Space --project="pbl-Work" --prod --token=ddo_gXWMGGxAPcS4t9HTVA454zT04uPkHF1koMsr --enterypoint=main.ts
        env:
          DENO_DEPLOY_TOKEN: ${{ secrets.PBL }}
